class TestBookData {
  final List<String> imageUrls;
  final List<String> thumbnailUrls;
  final String chapter;

  const TestBookData({
    required this.imageUrls,
    required this.thumbnailUrls,
    required this.chapter,
  });
}

const book1 = TestBookData(
    chapter: """
4 - PART · 1   .............  乱马来了
19 - PART · 2   .............  乱马的秘密
30 - PART · 3   .............  最讨厌男生
40 - PART · 4   .............  怎么也不会承认
50 - PART · 5   .............  给树上拿着水壶的女孩
60 - PART · 6   .............  心与身体
""",
    imageUrls: [
      "https://files.catbox.moe/lpwubd.png",
      "https://files.catbox.moe/77zudp.png",
      "https://files.catbox.moe/i83hi2.png",
      "https://files.catbox.moe/fan8ol.png",
      "https://files.catbox.moe/mepc2y.png",
      "https://files.catbox.moe/vb0n2u.png",
      "https://files.catbox.moe/aodzj3.png",
      "https://files.catbox.moe/fa2sl2.png",
      "https://files.catbox.moe/ymzvpn.png",
      "https://files.catbox.moe/z4dqt5.png",
      "https://files.catbox.moe/mciqlb.png",
      "https://files.catbox.moe/bsdczw.png",
      "https://files.catbox.moe/6hij7u.png",
      "https://files.catbox.moe/6ebxch.png",
      "https://files.catbox.moe/4704cy.png",
      "https://files.catbox.moe/xxk26l.png",
      "https://files.catbox.moe/wtepjy.png",
      "https://files.catbox.moe/nys6ce.png",
      "https://files.catbox.moe/6xwn3b.png",
      "https://files.catbox.moe/vpcn54.png",
      "https://files.catbox.moe/8hrna0.png",
      "https://files.catbox.moe/of92ch.png",
      "https://files.catbox.moe/c7pkei.png",
      "https://files.catbox.moe/ocqbew.png",
      "https://files.catbox.moe/furyyz.png",
      "https://files.catbox.moe/cbjwe2.png",
      "https://files.catbox.moe/yaffk0.png",
      "https://files.catbox.moe/8qdmo1.png",
      "https://files.catbox.moe/miwz1x.png",
      "https://files.catbox.moe/gshjg4.png",
      "https://files.catbox.moe/rgwu45.png",
      "https://files.catbox.moe/qj2see.png",
      "https://files.catbox.moe/48ed20.png",
      "https://files.catbox.moe/zo5gne.png",
      "https://files.catbox.moe/xjoles.png",
      "https://files.catbox.moe/bj7dmb.png",
      "https://files.catbox.moe/ymqvm5.png",
      "https://files.catbox.moe/dzi5x7.png",
      "https://files.catbox.moe/ae33we.png",
      "https://files.catbox.moe/iazoc6.png",
      "https://files.catbox.moe/mewd3b.png",
      "https://files.catbox.moe/vh4mcs.png",
      "https://files.catbox.moe/u236bb.png",
      "https://files.catbox.moe/okd9n5.png",
      "https://files.catbox.moe/udt0kg.png",
      "https://files.catbox.moe/xnh95p.png",
      "https://files.catbox.moe/fn15j7.png",
      "https://files.catbox.moe/6obh45.png",
      "https://files.catbox.moe/tw8hsx.png",
      "https://files.catbox.moe/cnm9hw.png",
      "https://files.catbox.moe/90h3w3.png",
      "https://files.catbox.moe/1bdfz6.png",
      "https://files.catbox.moe/3lnomy.png",
      "https://files.catbox.moe/cuqfj7.png",
      "https://files.catbox.moe/n82cgy.png",
      "https://files.catbox.moe/9butxa.png",
      "https://files.catbox.moe/jw0egn.png",
      "https://files.catbox.moe/e4t427.png",
      "https://files.catbox.moe/v35iky.png",
      "https://files.catbox.moe/62tyz2.png"
    ],
    thumbnailUrls: [
      "https://files.catbox.moe/iprlur.png",
      "https://files.catbox.moe/a7mkeh.png",
      "https://files.catbox.moe/wehmon.png",
      "https://files.catbox.moe/3vt2gu.png",
      "https://files.catbox.moe/7tkuit.png",
      "https://files.catbox.moe/ktrt8a.png",
      "https://files.catbox.moe/uk9c40.png",
      "https://files.catbox.moe/fd3zmu.png",
      "https://files.catbox.moe/nfedkq.png",
      "https://files.catbox.moe/dw9zpc.png",
      "https://files.catbox.moe/0ouoka.png",
      "https://files.catbox.moe/gfzban.png",
      "https://files.catbox.moe/zsykir.png",
      "https://files.catbox.moe/4l4z8g.png",
      "https://files.catbox.moe/tbwhgm.png",
      "https://files.catbox.moe/gtk2dx.png",
      "https://files.catbox.moe/6xs23n.png",
      "https://files.catbox.moe/sect8o.png",
      "https://files.catbox.moe/ewdk44.png",
      "https://files.catbox.moe/wrkoo8.png",
      "https://files.catbox.moe/f86ws8.png",
      "https://files.catbox.moe/x1j1ml.png",
      "https://files.catbox.moe/xlk934.png",
      "https://files.catbox.moe/uotsh3.png",
      "https://files.catbox.moe/829avw.png",
      "https://files.catbox.moe/rpi5an.png",
      "https://files.catbox.moe/jy18og.png",
      "https://files.catbox.moe/48kaz8.png",
      "https://files.catbox.moe/h0ejsm.png",
      "https://files.catbox.moe/vybzd0.png",
      "https://files.catbox.moe/aewrxy.png",
      "https://files.catbox.moe/1mr90i.png",
      "https://files.catbox.moe/mol905.png",
      "https://files.catbox.moe/mv7bfx.png",
      "https://files.catbox.moe/s8nh4q.png",
      "https://files.catbox.moe/5u53tg.png",
      "https://files.catbox.moe/od8r0e.png",
      "https://files.catbox.moe/cqxf70.png",
      "https://files.catbox.moe/k4ua0y.png",
      "https://files.catbox.moe/m5toia.png",
      "https://files.catbox.moe/bvdegw.png",
      "https://files.catbox.moe/qvjjdl.png",
      "https://files.catbox.moe/e2n3mc.png",
      "https://files.catbox.moe/6lf2xu.png",
      "https://files.catbox.moe/njuj51.png",
      "https://files.catbox.moe/erlcef.png",
      "https://files.catbox.moe/xoxhz7.png",
      "https://files.catbox.moe/9n6xr9.png",
      "https://files.catbox.moe/rqj4b4.png",
      "https://files.catbox.moe/6sz5y2.png",
      "https://files.catbox.moe/mtyrg0.png",
      "https://files.catbox.moe/4imp9k.png",
      "https://files.catbox.moe/e1apgj.png",
      "https://files.catbox.moe/1r2yjj.png",
      "https://files.catbox.moe/moir3h.png",
      "https://files.catbox.moe/wrwi25.png",
      "https://files.catbox.moe/zbztxw.png",
      "https://files.catbox.moe/cehwqd.png",
      "https://files.catbox.moe/2tnbbr.png",
      "https://files.catbox.moe/6qnk95.png"
    ]
);

// 图片是单页的. 用于测试合并双页
const book2 = TestBookData(
    chapter: """
4 - PART · 1   .............  乱马来了
19 - PART · 2   .............  乱马的秘密
30 - PART · 3   .............  最讨厌男生
40 - PART · 4   .............  怎么也不会承认
50 - PART · 5   .............  给树上拿着水壶的女孩
60 - PART · 6   .............  心与身体
""",
    imageUrls: [
      "https://files.catbox.moe/kvzt6t.jpg",
      "https://files.catbox.moe/0gp0mk.jpg",
      "https://files.catbox.moe/k78lod.jpg",
      "https://files.catbox.moe/yt85u3.jpg",
      "https://files.catbox.moe/d2zdy5.jpg",
      "https://files.catbox.moe/6zznxe.jpg",
      "https://files.catbox.moe/imjybn.jpg",
      "https://files.catbox.moe/z69kdr.jpg",
      "https://files.catbox.moe/1o3g3y.jpg",
      "https://files.catbox.moe/afgqek.jpg",
      "https://files.catbox.moe/a3gg16.jpg",
      "https://files.catbox.moe/q5qk8f.jpg",
      "https://files.catbox.moe/c242i0.jpg",
      "https://files.catbox.moe/uyh70s.jpg",
      "https://files.catbox.moe/bpyagl.jpg",
      "https://files.catbox.moe/aoz3l0.jpg",
      "https://files.catbox.moe/s9nftn.jpg",
      "https://files.catbox.moe/8hkuiv.jpg",
      "https://files.catbox.moe/c0ygrj.jpg",
      "https://files.catbox.moe/50fesl.jpg"
    ],
    thumbnailUrls: [
      "https://files.catbox.moe/hdm6oz.jpg",
      "https://files.catbox.moe/zfoys0.jpg",
      "https://files.catbox.moe/ihq1by.jpg",
      "https://files.catbox.moe/hs5z11.jpg",
      "https://files.catbox.moe/a0cquu.jpg",
      "https://files.catbox.moe/7jkzv7.jpg",
      "https://files.catbox.moe/t1wlyz.jpg",
      "https://files.catbox.moe/dotr4f.jpg",
      "https://files.catbox.moe/j3adjx.jpg",
      "https://files.catbox.moe/gd6u6q.jpg",
      "https://files.catbox.moe/cc22wc.jpg",
      "https://files.catbox.moe/8uxy0x.jpg",
      "https://files.catbox.moe/pp190t.jpg",
      "https://files.catbox.moe/gouco4.jpg",
      "https://files.catbox.moe/lqk77w.jpg",
      "https://files.catbox.moe/jivkm0.jpg",
      "https://files.catbox.moe/nwt9kb.jpg",
      "https://files.catbox.moe/nw76de.jpg",
      "https://files.catbox.moe/d9mbaf.jpg",
      "https://files.catbox.moe/twd18q.jpg"
    ]
);
